### ISSUE TITLE
build fails at cloning ezmlm-idx

### ISSUE THREAD

**Issue by jschmidt3786** [Maescool/docker-qmail#1]
```
****************************************************

     If you plan to use the vpopmail usage daemon
     run the following commands:

   cd vusaged && ./configure && make

     Then follow the INSTALL file to install

****************************************************

make[1]: Leaving directory `/usr/src/vpopmail-5.4.33'
Cloning into 'ezmlm-idx'...
tools/makemake: line 3: import: command not found
tools/makemake: line 4: from: command not found
tools/makemake: line 6: syntax error near unexpected token `('
tools/makemake: line 6: `re_include = re.compile('^\s*#include\s+"([^"]+)"\s*$', re.MULTILINE)'
The command '/bin/sh -c /app/setup/install.sh' returned a non-zero code: 2
```

I'm new to docker, and I don't see any recent activity on this repo.
I just thought I'd report, as it looks like you have put together a nice netqmail setup here.

**Comment by artbrock** [comment]
@jschmidt3786 It looks like there's a fork which may have fixed this issue by having git grab the version of ezmlm that was originally integrated in this package rather than just the newest version.

That forked repo is here: https://github.com/robreardon/docker-qmail

**Comment by Maescool** [comment]
Fixed this issue having the other sources now included, since some of them have disappeared from the net
